#pour les test
spring:
  application:
    name: eDeclare
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/halldb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: dan
    password: dan
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: michelmarieenyegue002@gmail.com
    password: enfvsmfofdszyjmy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
cloudinary:
  cloud-name: dsxc9oxqz
  api-key: 856951881528275
  api-secret: _azl3LT9y7nu0fx5vhnASXpPGQQ

  #Pour la production
#  spring:
#    application:
#      name: DeptManager
#    datasource:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: ${JDBC_DATASOURCE_URL}
#      username: ${JDBC_DATASOURCE_USERNAME}
#      password: ${JDBC_DATASOURCE_PASSWORD}
#    jpa:
#      show-sql: true
#      hibernate:
#        ddl-auto: update
#      database-platform: org.hibernate.dialect.MySQLDialect
#    servlet:
#      multipart:
#        max-file-size: 500MB
#        max-request-size: 500MB
#    mail:
#      host: ${MAIL_HOST}
#      port: ${MAIL_PORT}
#      username: ${MAIL_USERNAME}
#      password: ${MAIL_PASSWORD}
#      properties:
#        mail:
#          smtp:
#            auth: true
#            starttls:
#              enable: true
#              required: true
#            connectiontimeout: 5000
#            timeout: 5000
#  cloudinary:
#    cloud-name: ${CLOUDINARY_NAME}
#    api-key: ${CLOUDINARY_API_KEY}
#    api-secret: ${CLOUDINARY_API_SECRET}
